In [2]:
import numpy as np
import pandas as pd

In [6]:
data = pd.read_csv("spam.csv", encoding="latin1")
data

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [7]:
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [8]:
data.shape

(5572, 5)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [11]:
data.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [12]:
data.sample(5)

       v1                                                 v2
4028  ham           [Û_] anyway, many good evenings to u! s
1263  ham  Ok. No wahala. Just remember that a friend in ...
1566  ham                      I am late. I will be there at
1310  ham  I.ll always be there, even if its just in spir...
2967  ham             Mostly sports type..lyk footbl,crckt..

In [14]:
data.rename(columns={'v1':'target','v2':'text'},inplace=True)

In [15]:
data.sample(5)

     target                                               text
4643    ham                       Did u got that persons story
627     ham  Yup i thk they r e teacher said that will make...
2614    ham  Sir, hope your day is going smoothly. i really...
386     ham                    Customer place i will call you.
4205    ham                             Get the door, I'm here

In [16]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [19]:
data['target']=encoder.fit_transform(data['target'])

In [20]:
data.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [23]:
data.isnull().sum()

target    0
text      0
dtype: int64

In [24]:
data.duplicated().sum()

np.int64(403)

In [27]:
data=data.drop_duplicates(keep='first')

In [28]:
data.duplicated().sum()

np.int64(0)

In [30]:
data.shape

(5169, 2)